env_name: &env_name "Circles"
nature_params:
  max_animals: 500
  n_species_setpoint: 10
  max_timesteps: 1
  rel_advantage_ind: 3.0
  rel_advantage_spec: 1.0
  mutation_probs: (0.01, 0.02, 0.3, 0.3, 0.8, 0.0)
  syn_mutation_prob: 0.8
  syn_mut_type_probs: (0.9, 0.05, 0.05)
  weight_change_std: 0.1
  perturb_biases : False
  c_d: 1.0
  c_w: 0.4
  delta: 2.0
  gamma: 1.2
  established_species_thr: 5
  cull_ratio: 0.25
  parthenogenesis_rate: 0.1
  interspecies_mating_chance : 0.02
  metabolic_penalty: 0.001
  eval_repeats: 1000
  parallel: True
  n_workers: 10
  self_play: False
  save_logs: True
  log_every: 10
  lifetime_learning: True
  lr: 0.001
  n_learning_episodes: 1000

innovation_handler_params:
  maxlen: 300

animal_params:
  neuron_type: "relu"
  action_type: "Sigmoid"
  action_bounds: None
  action_noise: 0.0

blueprint_params:
  weight_init_std : 0.4
  orph_node_thr: 0.1
  max_neurons: 16
  max_weight_val: 5.0

logger_params:
  data_folder: "../../../data/evolved_models/Circles"
  log_folder: "../../../log/Circles"
  img_folder: "../../../img/Circles"
  render: False
  render_every: -1
  plot_every : 10

evolution_params:
  n_generations: 30

