env_name: &env_name "CDDM-v0"
nature_params:
  max_animals: 120
  max_species: 12
  max_timesteps: 300
  rel_advantage_ind: 3.0
  rel_advantage_spec: 1.0
  mutation_probs: (0.005, 0.005, 0.6, 0.6, 0.8, 0.0)
  syn_mutation_prob: 0.4
  syn_mut_type_probs: (0.9, 0.05, 0.05)
  weight_change_std: 0.05
  perturb_biases : False
  c_d: 1.0
  c_w: 0.4
  delta: 3.0
  gamma: 1.2
  established_species_thr: 5
  cull_ratio: 0.2
  parthenogenesis_rate: 0.25
  interspecies_mating_chance : 0.02
  metabolic_penalty: 0.0001
  eval_repeats: 101
  parallel: False
  num_workers: 10
  self_play: False
  num_reference_animals: 0
  save_logs: True
  log_every: 100

innovation_handler_params:
  maxlen: 300

animal_params:
  neuron_type: "relu"
  action_type: "MultiBinary"
  action_bounds: None
  action_noise: 0.00

logger_params:
  data_folder: "../../../data/evolved_models/CDDM-v0"
  log_folder: "../../../log/CDDM-v0"
  img_folder: "../../../img/CDDM-v0"
  render: False
  render_every: -1
  plot_every : 10

evolution_params:
  n_generations: 1000

